### ISSUE TITLE
Install error with RPI.GPIO   error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by DxPru** [kantlivelong/OctoPrint-PSUControl#178]
#### What were you doing?

1. installing PsuControl on pi4b with ubuntu server and octoprint in a venv --> got install error with RPI.GPIO
2. installing RPI.GPIO in the venv  with 'pip3 install RPI.GPIO' and 'pip install RPI.GPIO'
    -->  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

#### Operating System running OctoPrint 
      Ubuntu server 20.10 with Octoprint in a python3 venv

#### Link to octoprint.log with octoprnt.plugins.psucontrol set to DEBUG
2021-03-28 11:44:19,239 - octoprint.plugins.pluginmanager - INFO - Installing plugin from https://github.com/kantlivelong/OctoPrint-PSUControl/archive/master.zip
2021-03-28 11:44:28,588 - octoprint.plugins.discordremote - INFO - Presence: {"op": 3, "d": {"activities": [], "status": "online", "afk": false, "since": null}}
2021-03-28 11:44:37,372 - octoprint.plugins.pluginmanager - ERROR - Could not install plugin from https://github.com/kantlivelong/OctoPrint-PSUControl/archive/master.zip
Traceback (most recent call last):
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 738, in _command_install_archive
    returncode, stdout, stderr = self._call_pip(pip_args)
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 1414, in _call_pip
    return self._pip_caller.execute(*args, **kwargs)
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/pip.py", line 209, in execute
    return self.call(command, **kwargs)
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/commandline.py", line 243, in call
    all_stderr += process_stderr(p.stderr.readlines(timeout=0.5))
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/commandline.py", line 239, in process_stderr
    return process_lines(lines, self._log_stderr)
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/commandline.py", line 229, in process_lines
    processed = self._preprocess_lines(
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/pip.py", line 511, in _preprocess_lines
    return list(map(self._preprocess, lines))
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/pip.py", line 530, in _preprocess
    return to_unicode(clean_ansi(text))
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/commandline.py", line 57, in clean_ansi
    return _ANSI_REGEX.sub(b"", line.encode("latin1")).decode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 31: ordinal not in range(256)
2021-03-28 11:44:37,402 - octoprint.plugins.pluginmanager - ERROR - Reason: UnicodeEncodeError('latin-1', '  source/c_gpio.c: In function ‘setup’:\n', 31, 32, 'ordinal not in range(256)')
Traceback (most recent call last):
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 738, in _command_install_archive
    returncode, stdout, stderr = self._call_pip(pip_args)
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/plugins/pluginmanager/__init__.py", line 1414, in _call_pip
    return self._pip_caller.execute(*args, **kwargs)
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/pip.py", line 209, in execute
    return self.call(command, **kwargs)
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/commandline.py", line 243, in call
    all_stderr += process_stderr(p.stderr.readlines(timeout=0.5))
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/commandline.py", line 239, in process_stderr
    return process_lines(lines, self._log_stderr)
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/commandline.py", line 229, in process_lines
    processed = self._preprocess_lines(
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/pip.py", line 511, in _preprocess_lines
    return list(map(self._preprocess, lines))
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/pip.py", line 530, in _preprocess
    return to_unicode(clean_ansi(text))
  File "/home/ubuntu/octoprint/venv/lib/python3.8/site-packages/octoprint/util/commandline.py", line 57, in clean_ansi
    return _ANSI_REGEX.sub(b"", line.encode("latin1")).decode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 31: ordinal not in range(256)

**Comment by DxPru** [comment]
Installing RPI.GPIO with:
      export CFLAGS=-fcommon
      pip3 install RPi.GPIO
and then installing PsuControl

solved The Problem for me
