### ISSUE TITLE
Fail running on Pcduino3

### ISSUE THREAD

**Issue by pablogventura** [kantlivelong/OctoPrint-PSUControl#18]
I'm running Octoprint on a Pcduino3. It's supported? Sometimes PSUControl suddenly stops working. 
Log:

```
2017-03-20 14:21:24,064 - octoprint.plugin.core - ERROR - Something went wrong while retrieving package info data for module octoprint_psucontrol
Traceback (most recent call last):
  File "/home/pablo/OctoPrint/venv/local/lib/python2.7/site-packages/OctoPrint-1.3.2-py2.7.egg/octoprint/plugin/core.py", line 608, in _find_plugins_from_entry_points
    module_pkginfo = InstalledEntryPoint(entry_point)
  File "/home/pablo/OctoPrint/venv/local/lib/python2.7/site-packages/OctoPrint-1.3.2-py2.7.egg/octoprint/plugin/core.py", line 1335, in __init__
    pkginfo.Installed.__init__(self, package, metadata_version=metadata_version)
  File "/home/pablo/OctoPrint/venv/local/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg/pkginfo/installed.py", line 15, in __init__
    __import__(package)
  File "/home/pablo/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_psucontrol/__init__.py", line 11, in <module>
    import RPi.GPIO as GPIO
  File "/home/pablo/OctoPrint/venv/local/lib/python2.7/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
```

**Comment by kantlivelong** [comment]
Unsupported
