### ISSUE TITLE
Stops working arbitrarily

### ISSUE THREAD

**Issue by joseslo** [kantlivelong/OctoPrint-PSUControl#57]
I'm not sure if it's an issue of this plugin or an Octoprint issue. I've installed Octoprint in a Raspberry Pi 2 B+ with this plugin. After several hours running (I use to turn it on in the morning, and the issue usually occurs at night) the Octoprint system menu suddenly disappears. I don't know why but, when this happens, PSU control button (in the navbar) still is there but has no effect. I try to turn the printer off, the confirmation dialog appears normally, I confirm, but nothing happens, and the icon keeps in green, like nothing happened. If I go to a shell and set manually the GPIO pin, it works properly.

**Comment by kantlivelong** [comment]
Hi @joseslo,

I haven't seen or heard of this issue occurring. Could you provide log files?

**Comment by joseslo** [comment]
The issue regarding the system menu is similar to  [https://github.com/foosel/OctoPrint/issues/797](url), but the proposed solution seems not to work for me.

Here is the log file

`2017-08-27 14:39:05,466 - octoprint.filemanager.analysis - INFO - Starting analysis of local:AAE_pie_endstop_z.gcode
2017-08-27 14:41:21,854 - octoprint.filemanager.analysis - INFO - Analysis of entry local:AAE_pie_endstop_z.gcode finished, needed 136.39s
2017-08-27 14:50:00,352 - octoprint.server - INFO - ******************************************************************************
2017-08-27 14:50:00,357 - octoprint.server - INFO - Starting OctoPrint 1.3.4 (master branch)
2017-08-27 14:50:00,360 - octoprint.server - INFO - ******************************************************************************
2017-08-27 14:50:00,814 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-08-27 14:50:10,451 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 17 mixin implementations, 17 hook handlers
2017-08-27 14:50:10,651 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-08-27 14:50:12,443 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 17 mixin implementations, 17 hook handlers
2017-08-27 14:50:12,737 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2017-08-27 14:50:32,505 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2017-08-27 14:50:33,579 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-27 14:50:43,167 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -m pip" as command to invoke pip
2017-08-27 14:50:51,948 - octoprint.util.pip - INFO - Version of pip is 8.1.1
2017-08-27 14:50:51,952 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages, --user flag needed => no, virtual env => yes
2017-08-27 14:50:51,973 - octoprint.plugin.core - INFO - Initialized 17 plugin implementation(s)
2017-08-27 14:50:52,001 - octoprint.plugins.actioncommands - INFO - Add command definition 'action:' = 
2017-08-27 14:50:52,030 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/util/__init__.py:591: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value_source != value_target:

2017-08-27 14:50:52,130 - octoprint.plugins.psucontrol - INFO - Running RPi.GPIO version 0.6.3
2017-08-27 14:50:52,134 - octoprint.plugins.psucontrol - INFO - Using GPIO for On/Off
2017-08-27 14:50:52,137 - octoprint.plugins.psucontrol - INFO - Configuring GPIO for pin 26
2017-08-27 14:50:52,170 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Action Commands (0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_actioncommands
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/announcements
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/corewizard
|  Cost Plugin (0.1.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_cost
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_customControl
|  Detailed Progress Plugin (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_detailedprogress
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/discovery
|  Enclosure Plugin (3.51) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_enclosure
|  LED Strip Control (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_LEDStripControl
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/pluginmanager
|  PSU Control (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_psucontrol
|  Pushbullet (0.1.9) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octobullet
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/softwareupdate
|  STL Viewer (0.3.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stlviewer
|  TouchUI (0.3.8) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/virtual_printer
2017-08-27 14:50:52,184 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-27 14:50:52,252 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2017-08-27 14:50:52,457 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2017-08-27 14:50:56,820 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-08-27 14:50:56,964 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for _http._tcp
2017-08-27 14:50:57,145 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for _octoprint._tcp
2017-08-27 14:50:57,178 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2017-08-27 14:50:57,224 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2017-08-27 14:50:58,349 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-08-27 14:50:58,624 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 0.99s
2017-08-27 14:50:59,719 - octoprint.plugins.octobullet - INFO - Connected to PushBullet
2017-08-27 14:50:59,887 - octoprint.plugins.stlviewer - INFO - STL Viewer loaded!
2017-08-27 14:50:59,904 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2017-08-27 14:51:00,824 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.1
2017-08-27 14:51:01,185 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': ''}
2017-08-27 14:51:01,807 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-08-27 14:51:01,979 - octoprint.plugins.pluginmanager - INFO - Loaded plugin notices data from http://plugins.octoprint.org/notices.json
2017-08-27 14:51:02,189 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-27 14:51:02,733 - octoprint.util.comm - INFO - Printer reports firmware name "ANET_A8_20160525  http://www.anet3d.com/"
2017-08-27 14:51:07,444 - octoprint.plugins.announcements - INFO - Loaded channel _releases from http://octoprint.org/feeds/releases.xml in 0.44s
2017-08-27 14:51:10,053 - octoprint.plugins.announcements - INFO - Loaded channel _blog from http://octoprint.org/feeds/octoblog.xml in 0.42s
2017-08-27 14:51:12,089 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from http://plugins.octoprint.org/feed.xml in 0.31s
2017-08-27 14:51:15,309 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from http://octoprint.org/feeds/octopi.xml in 0.42s
2017-08-27 14:52:37,615 - octoprint.server.preemptive_cache - INFO - ... done in 96.43s
2017-08-27 14:52:37,637 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http:///'}
2017-08-27 14:53:13,356 - octoprint.server.preemptive_cache - INFO - ... done in 35.72s
2017-08-27 15:40:45,525 - octoprint.filemanager.analysis - INFO - Starting analysis of local:AAE_viga_diagonal_larga.gcode
2017-08-27 15:42:06,501 - octoprint.filemanager.analysis - INFO - Starting analysis of local:AAE_viga_diagonal_larga.gcode
2017-08-27 15:43:07,990 - octoprint.filemanager.analysis - INFO - Starting analysis of local:AAE_viga_diagonal_larga.gcode
2017-08-27 15:44:42,515 - octoprint.filemanager.analysis - INFO - Starting analysis of local:AAE_viga_diagonal_larga.gcode
2017-08-27 15:45:46,579 - octoprint.plugins.detailedprogress - INFO - Printing started. Detailed progress started.
2017-08-27 15:45:46,604 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-08-27 15:45:46,693 - octoprint.plugins.enclosure - INFO - Writing on gpio: 19 value False
2017-08-27 15:59:05,627 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.1.1
2017-08-27 15:59:09,171 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.1
2017-08-27 16:14:54,952 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.1.1
2017-08-27 17:24:26,488 - tornado.access - WARNING - 404 GET /muieblackcat (127.0.0.1) 126.11ms
2017-08-27 17:24:27,145 - tornado.access - WARNING - 404 GET //phpMyAdmin/scripts/setup.php (127.0.0.1) 107.43ms
2017-08-27 21:33:38,976 - octoprint.util.comm - INFO - Finished in 20872.428 s.
2017-08-27 21:33:38,994 - octoprint.plugins.detailedprogress - INFO - Printing stopped. Detailed progress stopped.
2017-08-27 21:33:39,073 - octoprint.plugins.octobullet - ERROR - Exception while fetching snapshot from webcam, sending only a note: [Errno socket error] [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octobullet/__init__.py", line 345, in _send_message_with_webcam_image
    snapshot_path, headers = urllib.urlretrieve(snapshot_url)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 111] Connection refused
2017-08-27 21:33:56,415 - octoprint.filemanager.analysis - INFO - Starting analysis of local:AAE_viga_diagonal_larga.gcode
2017-08-27 21:35:27,814 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.1
2017-08-27 21:35:48,230 - tornado.access - WARNING - 403 GET /api/users (127.0.0.1) 148.41ms
2017-08-27 21:35:48,426 - tornado.access - WARNING - 403 GET /api/system/commands (127.0.0.1) 155.56ms
2017-08-27 21:35:50,024 - tornado.access - WARNING - 403 GET /plugin/announcements/channels (127.0.0.1) 201.38ms
2017-08-27 21:35:50,216 - tornado.access - WARNING - 403 GET /api/plugin/pluginmanager (127.0.0.1) 165.21ms
2017-08-27 21:36:15,325 - tornado.access - WARNING - 403 POST /api/plugin/psucontrol (127.0.0.1) 216.72ms
2017-08-27 21:36:17,535 - tornado.access - WARNING - 403 POST /api/plugin/psucontrol (127.0.0.1) 188.25ms
2017-08-27 21:37:23,000 - octoprint.util.comm - ERROR - Unexpected error while reading from serial port
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/util/comm.py", line 1827, in _readline
    ret = self._serial.readline()
  File "build/bdist.linux-armv7l/egg/serial/serialposix.py", line 475, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2017-08-27 21:37:23,074 - octoprint.util.comm - ERROR - Please see https://bit.ly/octoserial for possible reasons of this.
2017-08-27 21:45:40,707 - octoprint.filemanager.analysis - INFO - Analysis of entry local:AAE_viga_diagonal_larga.gcode finished, needed 704.29s
2017-08-28 06:23:34,098 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.1.1
2017-08-28 06:23:34,756 - octoprint.server - INFO - Shutting down...
2017-08-28 06:23:35,054 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2017-08-28 06:23:35,058 - octoprint.events - INFO - Event loop shut down
2017-08-28 06:23:35,146 - octoprint.plugin - ERROR - Error while calling plugin LEDStripControl
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugin/__init__.py", line 229, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_LEDStripControl/__init__.py", line 123, in on_shutdown
    self._pigpiod.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
2017-08-28 06:23:35,362 - octoprint.server - INFO - Goodbye!
2017-08-28 06:24:19,071 - octoprint.server - INFO - ******************************************************************************
2017-08-28 06:24:19,077 - octoprint.server - INFO - Starting OctoPrint 1.3.4 (master branch)
2017-08-28 06:24:19,080 - octoprint.server - INFO - ******************************************************************************
2017-08-28 06:24:19,533 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-08-28 06:24:29,339 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 17 mixin implementations, 17 hook handlers
2017-08-28 06:24:29,544 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-08-28 06:24:31,333 - octoprint.plugin.core - INFO - Found 17 plugin(s) providing 17 mixin implementations, 17 hook handlers
2017-08-28 06:24:31,578 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2017-08-28 06:24:51,478 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2017-08-28 06:24:52,505 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-08-28 06:25:02,003 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -m pip" as command to invoke pip
2017-08-28 06:25:10,923 - octoprint.util.pip - INFO - Version of pip is 8.1.1
2017-08-28 06:25:10,928 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages, --user flag needed => no, virtual env => yes
2017-08-28 06:25:10,947 - octoprint.plugin.core - INFO - Initialized 17 plugin implementation(s)
2017-08-28 06:25:10,975 - octoprint.plugins.actioncommands - INFO - Add command definition 'action:' = 
2017-08-28 06:25:11,003 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/util/__init__.py:591: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value_source != value_target:

2017-08-28 06:25:11,103 - octoprint.plugins.psucontrol - INFO - Running RPi.GPIO version 0.6.3
2017-08-28 06:25:11,105 - octoprint.plugins.psucontrol - INFO - Using GPIO for On/Off
2017-08-28 06:25:11,108 - octoprint.plugins.psucontrol - INFO - Configuring GPIO for pin 26
2017-08-28 06:25:11,145 - octoprint.plugin.core - INFO - 17 plugin(s) registered with the system:
|  Action Commands (0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_actioncommands
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/announcements
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/corewizard
|  Cost Plugin (0.1.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_cost
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_customControl
|  Detailed Progress Plugin (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_detailedprogress
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/discovery
|  Enclosure Plugin (3.51) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_enclosure
|  LED Strip Control (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_LEDStripControl
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/pluginmanager
|  PSU Control (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_psucontrol
|  Pushbullet (0.1.9) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octobullet
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/softwareupdate
|  STL Viewer (0.3.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stlviewer
|  TouchUI (0.3.8) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/virtual_printer
2017-08-28 06:25:11,156 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-08-28 06:25:11,237 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2017-08-28 06:25:11,424 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2017-08-28 06:25:17,608 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-08-28 06:25:17,872 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for _http._tcp
2017-08-28 06:25:18,127 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for _octoprint._tcp
2017-08-28 06:25:18,192 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2017-08-28 06:25:18,215 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2017-08-28 06:25:18,991 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-08-28 06:25:20,770 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 1.7s
2017-08-28 06:25:22,746 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-08-28 06:25:22,892 - octoprint.plugins.octobullet - INFO - Connected to PushBullet
2017-08-28 06:25:23,194 - octoprint.plugins.stlviewer - INFO - STL Viewer loaded!
2017-08-28 06:25:23,680 - octoprint.util.comm - INFO - Printer reports firmware name "ANET_A8_20160525  http://www.anet3d.com/"
2017-08-28 06:25:24,488 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from http://plugins.octoprint.org/plugins.json
2017-08-28 06:25:25,832 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': ''}
2017-08-28 06:25:30,680 - octoprint.plugins.pluginmanager - INFO - Loaded plugin notices data from http://plugins.octoprint.org/notices.json
2017-08-28 06:25:31,947 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-08-28 06:25:33,430 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.1
2017-08-28 06:25:38,068 - octoprint.plugins.announcements - INFO - Loaded channel _releases from http://octoprint.org/feeds/releases.xml in 0.46s
2017-08-28 06:25:45,413 - octoprint.plugins.announcements - INFO - Loaded channel _blog from http://octoprint.org/feeds/octoblog.xml in 5.5s
2017-08-28 06:25:47,588 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from http://plugins.octoprint.org/feed.xml in 0.32s
2017-08-28 06:25:50,604 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from http://octoprint.org/feeds/octopi.xml in 0.47s
2017-08-28 06:27:07,116 - octoprint.server.preemptive_cache - INFO - ... done in 101.28s
2017-08-28 06:27:07,142 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': ''}
2017-08-28 06:27:42,477 - octoprint.server.preemptive_cache - INFO - ... done in 35.34s
2017-08-28 06:34:37,182 - octoprint.plugins.enclosure - INFO - Writing on gpio: 19 value False`

**Comment by kantlivelong** [comment]
I see a handful of errors/warning in that log but don't think they would affect the nav bar. Could you try disabling all 3rd party plugins (including this one) and see if you can replicate the problem?

**Comment by kantlivelong** [comment]
Closing. Re-open if still an issue.
